name: Gatsby Publish

on:
  push:
    branches:
      - main

env:
  CXXFLAGS: "--std=c++14"
  GATSBY_CONTENTFUL_OFFLINE: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages